const pool = require("../config/database");

const schoolJoin = `JOIN students st_school ON st_school.id = sr.student_id AND st_school.school_id = $SCHOOL`;

const createResult = async (data, schoolId, client = pool) => {
    const q = `INSERT INTO student_results (student_id,teacher_assignment_id,session_id,term_id,ca_score,exam_score,total_score,grade,remark)
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 WHERE EXISTS (SELECT 1 FROM students s WHERE s.id=$1 AND s.school_id=$10) AND EXISTS (SELECT 1 FROM teacher_assignments ta JOIN teachers t ON t.id=ta.teacher_id JOIN users u ON u.id=t.user_id WHERE ta.id=$2 AND u.school_id=$10) RETURNING *`;
    const r=await client.query(q,[data.student_id,data.teacher_assignment_id,data.session_id,data.term_id,data.ca_score,data.exam_score,data.total_score,data.grade,data.remark,schoolId]); return r.rows[0];
};

const getResultById = async (id, schoolId) => { const r=await pool.query(`SELECT sr.id,s.admission_number,CONCAT(s.surname,' ',s.first_name) student_name,sub.subject_name,c.class_name,a.arm_name,ac.session_name,t.term_name,sr.ca_score,sr.exam_score,sr.total_score,sr.grade,sr.remark FROM student_results sr JOIN students s ON s.id=sr.student_id JOIN teacher_assignments ta ON ta.id=sr.teacher_assignment_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id JOIN subjects sub ON sub.id=ta.subject_id JOIN classes c ON c.id=ta.class_id LEFT JOIN arms a ON a.id=ta.arm_id JOIN academic_sessions ac ON ac.id=sr.session_id JOIN terms t ON t.id=sr.term_id WHERE sr.id=$1 AND u.school_id=$2 AND s.school_id=$2`,[id,schoolId]); return r.rows[0]; };

const getExistingResult = async (studentId, teacherAssignmentId, sessionId, termId, schoolId, client=pool) => { const r=await client.query(`SELECT sr.* FROM student_results sr JOIN students s ON s.id=sr.student_id JOIN teacher_assignments ta ON ta.id=sr.teacher_assignment_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id WHERE sr.student_id=$1 AND sr.teacher_assignment_id=$2 AND sr.session_id=$3 AND sr.term_id=$4 AND s.school_id=$5 AND u.school_id=$5 LIMIT 1`,[studentId,teacherAssignmentId,sessionId,termId,schoolId]); return r.rows[0]; };

const updateResult = async (id,data,schoolId,client=pool) => { const r=await client.query(`UPDATE student_results sr SET ca_score=$1,exam_score=$2,total_score=$3,grade=$4,remark=$5,updated_at=CURRENT_TIMESTAMP FROM students s JOIN teacher_assignments ta ON ta.id=sr.teacher_assignment_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id WHERE sr.id=$6 AND sr.student_id=s.id AND s.school_id=$7 AND u.school_id=$7 RETURNING sr.*`,[data.ca_score,data.exam_score,data.total_score,data.grade,data.remark,id,schoolId]); return r.rows[0]; };

const getStudentsForResultEntry = async (teacherAssignmentId,schoolId) => { const r=await pool.query(`SELECT s.id,s.admission_number,CONCAT(s.surname,' ',s.first_name,CASE WHEN s.middle_name IS NOT NULL AND s.middle_name<>'' THEN ' '||s.middle_name ELSE '' END) student_name,sr.id result_id,sr.ca_score,sr.exam_score,sr.total_score,sr.grade,sr.remark,sr.position FROM students s JOIN student_enrollments se ON se.student_id=s.id JOIN teacher_assignments ta ON ta.class_id=se.class_id AND (ta.arm_id=se.arm_id OR (ta.arm_id IS NULL AND se.arm_id IS NULL)) AND ta.session_id=se.session_id LEFT JOIN student_results sr ON sr.student_id=s.id AND sr.teacher_assignment_id=ta.id AND sr.session_id=ta.session_id AND sr.term_id=ta.term_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id WHERE ta.id=$1 AND s.school_id=$2 AND u.school_id=$2 AND se.enrollment_status='Active' ORDER BY s.surname,s.first_name`,[teacherAssignmentId,schoolId]); return r.rows; };

const updatePositions = async (teacherAssignmentId,sessionId,termId,schoolId,client=pool) => { const r=await client.query(`WITH ranked AS (SELECT sr.id,DENSE_RANK() OVER(ORDER BY sr.total_score DESC) position FROM student_results sr JOIN students s ON s.id=sr.student_id JOIN teacher_assignments ta ON ta.id=sr.teacher_assignment_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id WHERE sr.teacher_assignment_id=$1 AND sr.session_id=$2 AND sr.term_id=$3 AND s.school_id=$4 AND u.school_id=$4) UPDATE student_results sr SET position=ranked.position FROM ranked WHERE sr.id=ranked.id RETURNING sr.id,sr.student_id,sr.total_score,sr.position`,[teacherAssignmentId,sessionId,termId,schoolId]); return r.rows; };

const getStudentResultReport = async (studentId,sessionId,termId,schoolId) => { const r=await pool.query(`SELECT s.id student_id,s.admission_number,se.class_id,se.arm_id,CONCAT(s.surname,' ',s.first_name,CASE WHEN s.middle_name IS NOT NULL AND s.middle_name<>'' THEN ' '||s.middle_name ELSE '' END) student_name,c.class_name,a.arm_name,ac.session_name,t.term_name,sub.subject_name,sr.ca_score,sr.exam_score,sr.total_score,sr.grade,sr.remark,sr.position FROM student_results sr JOIN students s ON sr.student_id=s.id JOIN teacher_assignments ta ON sr.teacher_assignment_id=ta.id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id JOIN subjects sub ON ta.subject_id=sub.id JOIN student_enrollments se ON se.student_id=s.id AND se.session_id=sr.session_id AND se.class_id=ta.class_id AND (se.arm_id=ta.arm_id OR (se.arm_id IS NULL AND ta.arm_id IS NULL)) JOIN classes c ON se.class_id=c.id LEFT JOIN arms a ON se.arm_id=a.id JOIN academic_sessions ac ON sr.session_id=ac.id JOIN terms t ON sr.term_id=t.id WHERE sr.student_id=$1 AND sr.session_id=$2 AND sr.term_id=$3 AND s.school_id=$4 AND u.school_id=$4 ORDER BY sub.subject_name`,[studentId,sessionId,termId,schoolId]); return r.rows; };

const getOverallClassRankings = async (classId,armId,sessionId,termId,schoolId) => { const r=await pool.query(`WITH student_totals AS (SELECT sr.student_id,SUM(sr.total_score) total_score,COUNT(sr.id) number_of_subjects,ROUND(AVG(sr.total_score),2) average_score FROM student_results sr JOIN teacher_assignments ta ON sr.teacher_assignment_id=ta.id JOIN students s ON s.id=sr.student_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id JOIN student_enrollments se ON se.student_id=sr.student_id AND se.session_id=sr.session_id AND se.class_id=ta.class_id AND (se.arm_id=ta.arm_id OR (se.arm_id IS NULL AND ta.arm_id IS NULL)) WHERE ta.class_id=$1 AND (ta.arm_id=$2 OR (ta.arm_id IS NULL AND $2 IS NULL)) AND sr.session_id=$3 AND sr.term_id=$4 AND se.enrollment_status='Active' AND s.school_id=$5 AND u.school_id=$5 GROUP BY sr.student_id) SELECT student_id,total_score,number_of_subjects,average_score,DENSE_RANK() OVER(ORDER BY average_score DESC,total_score DESC) overall_position FROM student_totals ORDER BY overall_position,student_id`,[classId,armId,sessionId,termId,schoolId]); return r.rows; };

const getClassResultSheet = async (classId,armId,sessionId,termId,schoolId) => { const r=await pool.query(`SELECT s.id student_id,s.admission_number,CONCAT(s.surname,' ',s.first_name,CASE WHEN s.middle_name IS NOT NULL AND s.middle_name<>'' THEN ' '||s.middle_name ELSE '' END) student_name,COUNT(sr.id) number_of_subjects,SUM(sr.total_score) total_score,ROUND(AVG(sr.total_score),2) average_score FROM students s JOIN student_enrollments se ON se.student_id=s.id LEFT JOIN student_results sr ON sr.student_id=s.id AND sr.session_id=$3 AND sr.term_id=$4 LEFT JOIN teacher_assignments ta ON ta.id=sr.teacher_assignment_id AND ta.class_id=$1 AND (ta.arm_id=$2 OR (ta.arm_id IS NULL AND $2 IS NULL)) JOIN users u ON u.id=s.user_id WHERE se.class_id=$1 AND (se.arm_id=$2 OR (se.arm_id IS NULL AND $2 IS NULL)) AND se.session_id=$3 AND se.enrollment_status='Active' AND s.school_id=$5 AND u.school_id=$5 GROUP BY s.id,s.admission_number,s.surname,s.first_name,s.middle_name ORDER BY average_score DESC NULLS LAST,total_score DESC NULLS LAST,student_name`,[classId,armId,sessionId,termId,schoolId]); return r.rows; };

const getClassBroadsheet = async (classId,armId,sessionId,termId,schoolId) => { const r=await pool.query(`SELECT s.id student_id,s.admission_number,CONCAT(s.surname,' ',s.first_name,CASE WHEN s.middle_name IS NOT NULL AND s.middle_name<>'' THEN ' '||s.middle_name ELSE '' END) student_name,sub.id subject_id,sub.subject_name,sr.total_score FROM student_results sr JOIN students s ON s.id=sr.student_id JOIN teacher_assignments ta ON ta.id=sr.teacher_assignment_id JOIN teachers tch ON tch.id=ta.teacher_id JOIN users u ON u.id=tch.user_id JOIN subjects sub ON sub.id=ta.subject_id JOIN student_enrollments se ON se.student_id=s.id AND se.class_id=ta.class_id AND se.session_id=sr.session_id AND (se.arm_id=ta.arm_id OR (se.arm_id IS NULL AND ta.arm_id IS NULL)) WHERE ta.class_id=$1 AND (ta.arm_id=$2 OR (ta.arm_id IS NULL AND $2 IS NULL)) AND sr.session_id=$3 AND sr.term_id=$4 AND se.enrollment_status='Active' AND s.school_id=$5 AND u.school_id=$5 ORDER BY s.surname,s.first_name,sub.subject_name`,[classId,armId,sessionId,termId,schoolId]); return r.rows; };

module.exports={createResult,getResultById,getExistingResult,updateResult,getStudentsForResultEntry,updatePositions,getStudentResultReport,getOverallClassRankings,getClassResultSheet,getClassBroadsheet};